"""Phase 5: Report Generation — compile all phases into a markdown report.

This is a pure data assembly step — no LLM calls. It takes the accumulated
state from all previous phases and formats it into a structured report.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from langgraph_portfolio.projects.project_12_analyst.state import InvestmentState


REPORTS_DIR = Path(__file__).parent.parent / "reports"


def _format_list(items: list, prefix: str = "- ") -> str:
    """Format a list of items as markdown bullets."""
    if not items:
        return "_None identified_"
    return "\n".join(f"{prefix}{item}" for item in items)


def build_report_content(state: InvestmentState) -> str:
    """Build the full markdown report from state."""
    ticker = state["ticker"]
    company = state.get("company_name", ticker)
    today = date.today().isoformat()

    return f"""# Investment Analysis: {ticker} — {company}

**Date:** {today}

---

## Executive Summary

{state.get('investment_thesis', '_No thesis generated_')}

---

## Financial Data Overview

{state.get('data_summary', '_No data summary available_')}

---

## Profitability Analysis

{state.get('profitability_analysis', '_Not completed_')}

---

## Valuation

{state.get('valuation_analysis', '_Not completed_')}

---

## Growth Assessment

{state.get('growth_analysis', '_Not completed_')}

---

## Bull/Bear Debate

{state.get('debate_transcript', '_Debate not run_')}

### Key Disagreements

{_format_list(state.get('key_disagreements', []))}

---

## Risk Factors

{_format_list(state.get('risk_factors', []))}

## Catalysts

{_format_list(state.get('catalysts', []))}

## Confidence Level: {state.get('confidence_level', 'N/A')}

---

_Report generated by Investment Committee (Project 12)_
"""


def generate_report(state: InvestmentState) -> dict:
    """LangGraph node: generate and save the markdown report."""
    ticker = state["ticker"]
    today = date.today().isoformat()
    filename = f"{ticker}_{today}.md"

    content = build_report_content(state)

    # Ensure reports directory exists
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / filename
    report_path.write_text(content, encoding="utf-8")

    return {
        "report_path": str(report_path),
        "current_phase": "complete",
        "_report_content": content,  # For testing; not part of InvestmentState
    }
